export const JOB_TYPES = {
  FETCH_CONTENT: "FETCH_CONTENT",
  GENERATE_POST: "GENERATE_POST",
  PUBLISH_POST: "PUBLISH_POST",
  POST_TO_LINKEDIN: "POST_TO_LINKEDIN",
  ALLOCATE_SLOTS: "ALLOCATE_SLOTS",
};
